# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2041d930579ab100b4b657223860837ed0f1bd8c5d646130ffbed908ed425b9bdf6077e0c8a262a33888b36d7011435ac6150f7ba608732d8771dfba48fa413

test:
  secret_key_base: 7f0904157be66fcbe2104eea7a5cb0e04df9f73fc87fce2d692d026e8f7f56f859e4847a83ad3eb6fa61e9ec7e738569bd97783f87ead79339d480fd4d5a9d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
